name: Build CyberPS2 Cloud

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Clonar Motor PS2 (Play!)
        run: |
          git clone --recursive https://github.com/jpd002/Play-
          
      - name: Inyectar Modificaciones (Fase Futura)
        run: |
          echo "En el siguiente paso inyectaremos tu código de VPS aquí"

      - name: Compilar APK
        working-directory: ./Play-/project/Android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Subir APK Resultante
        uses: actions/upload-artifact@v4
        with:
          name: CyberPS2-V1-Alpha
          path: Play-/project/Android/app/build/outputs/apk/debug/app-debug.apk
